services:
  collage:
    build: .
    container_name: collage-home
    ports:
      - "55555:8080"
    restart: unless-stopped
    environment:
      - MATRIX_HOMESERVER_URL=${MATRIX_HOMESERVER_URL:-https://matrix.techietable.com}
      - MATRIX_ACCESS_TOKEN=${MATRIX_ACCESS_TOKEN}
      - MATRIX_ROOM_ID=${MATRIX_ROOM_ID}
